config/routes.rb
Rails.application.routes.draw do




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/nuevopost', to: 'posts#new'
  root 'posts#index'


  resources :users
  resources :posts
  resources :comments


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments


  validates :user_id, presence: true
  validates :tittle, presence: true
  validates :content, presence: true, length: {minimum: 250}
  default_scope -> { order(created_at: :desc) }



end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 10}, uniqueness: {case_sensitive: false}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX},
      uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password , presence: true, length: {minimum: 6}



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include PostsHelper
  include CommentsHelper
  #holi
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def new

  end

  def create
    flash[:success] = "Has comentado correctamente"
    @user = User.find(current_user.id)
    @post = Post.find(session[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = @user.id
    @comment.save
    redirect_to post_path(@post)

  end

  private
  def comment_params
    params.require(:session).permit(:content)

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.all
   sacar_caracteres(@post)



  end
  def new
    #holaaaa mundo jejej
  @post = Post.new
  end


  def create

    @user = User.find(current_user.id)
    @post = @user.posts.build(post_params)
    if @post.save
      flash[:success] = "Tu Post se ha creado correctamente"

      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show

    @post = Post.find(params[:id])
    post_id(@post)
    @comment = @post.comments

  end

  def update
  @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Tu Post se ha editado correctamente"
      redirect_to root_path
    else
      render 'edit'
    end
  end


  def edit
    @post = Post.find(params[:id])

  end
  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post borrado correctamente"
    redirect_to root_path

  end

  private
  def post_params
    params.require(:post).permit(:tittle, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Has iniciado Sesión correctamente"
      log_in(user)
      redirect_to root_path

    else
      flash.now[:danger] = "Email invalido /Contraseña inválida "
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,only: [:edit, :update]
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts

  end
  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "Te has registrado correctamente"
      redirect_to root_path

    else
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Perfil actualizado"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


  def logged_in_user
    unless logged_in?
      store_url
      flash[:danger] = "Porfavor loggearse"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to login_url unless currect_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },

    }

    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(render_options = {})
    markdown = Redcarpet::Markdown.new(renderer, extensions = {})

    markdown.render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def post_id(post)

    session[:post_id] = post.id

  end




end

app/helpers/posts_helper.rb
module PostsHelper
  include SessionsHelper

  def blog_belongs_to_user?(blog)
    current_user.id == blog.user_id
  end

  def timer(t)
    aux = t.split(" ")

    if aux.count == 2
      if aux[1] == "minutes"
        aux[1] = "minutos"
      elsif aux[1] == "minute"
        aux[1] = "Minuto"
        else
        aux[1] = "dias"
      end

    elsif aux.count == 3
      aux[0] = "alrededor de "
      aux[2] = "horas"
    elsif aux.count == 4
      aux[0] = "menos"
      aux[1] = "de"
      aux[2] = "un"
      aux[3] = "Minuto"


    end

    aux.join(" ")
  end

  def sacar_caracteres(array)

    array.each do |f|
        aux2 = []
        aux = f.content.split("")
        for i in 0..249
          aux2[i] = aux[i]
        end
        f.content = aux2.join("")
    end
    array
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def currect_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def store_url
    session[:forwarding_url] = request.original_url if request.get?
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
  

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "INICIO", root_path%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "Nuevo post",nuevopost_path %></li>
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Perfil", current_user %></li>
            <li><%= link_to "Configuracion", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Salir", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Iniciar sesión", login_path %></li>
            <li><%= link_to "Registrarse", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> main"><%= message %></div>
    <% end %>


    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <%= render 'shared/error_messages_post' %>
    <%= f.label :tittle %>
    <%= f.text_field :tittle %>

    <%= f.label :content%>

    <%= f.text_area :content, class: 'textarea' %>
    <%= f.submit @post.new_record? ? "Crear post" : "Editar post" , class: 'btn btn-primary'%>
<% end %>

app/views/posts/edit.html.erb
<div class="row post">
  <div class="col-md-6 col-md-offset-2">
    <%= render 'form' %>
  </div>

</div>

app/views/posts/index.html.erb
<div class="row index">
  <div class="col-md-6 col-md-offset-2">
    <% if @post == [] %>
        <h2>No hay ningún blog en el momento</h2>
      <% else %>
        <% @post.each do |f| %>
          <div class="row">
            <div class="col-md-6 col-md-offset-1" >

              <div class="panel panel-default principal">
                <div class="panel-heading principal" >

                  <h3><%= link_to f.tittle, post_path(f) %></h3>
                  <% user = User.find(f.user_id)%>

                  <h4>Publicado por <%= user.name %> hace <%= timer(time_ago_in_words(f.created_at)) %></h4>

                </div>
                <div class="panel-body wrap">
                  <p><%= markdown(f.content) %>...</p>

                  <% if logged_in?  %>
                    <% if current_user.id == f.user_id %>
                    <%= link_to "Eliminar", f , method: :delete, data: { confirm:"Estas seguro?"}
                    %>   <%= link_to "Editar",edit_post_path(f)%>

                    <% end %>
                  <% end %>
                  <p></p>
                </div><s></s>
              </div>
            </div>
          </div>
        <% end %>
   <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row post">
  <div class="col-md-6 col-md-offset-2">
    <%= render 'form' %>
  </div>

</div>

app/views/posts/show.html.erb
<div class="row index">
  <div class="col-md-6 col-md-offset-2">
        <div class="row">
          <div class="col-md-6 col-md-offset-1" >
            <div class="panel panel-default principal">
              <div class="panel-heading principal">
                <h3><%= @post.tittle %></h3>
              </div>
              <div class="panel-body wrap">
                <p><%= markdown(@post.content) %></p>
              </div>
              <h2>Comentarios</h2>
            </div>
            <% @comment.each do |c| %>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <% user = User.find(c.user_id) %>
                    <p> El usuario <%= user.name %> comentó hace <%= timer(time_ago_in_words(c.created_at)) %></p>
                  </div>
                  <div class="panel-body wrap">
                    <p><%= c.content %></p>
                  </div><s></s>
                </div>
            <% end %>
            <% if logged_in? %>
              <%= form_for(:session, url: comments_path) do |c| %>
              <%= c.label "Comentar"  %>
              <%= c.text_area :content, class: 'form-control' %>
              <%= c.submit "Comentar", class: 'btn btn-primary' %>
              <% end  %>
            <% end %>

          </div>
        </div>

  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul class="errors">
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_error_messages_post.html.erb
<% if @post.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@post.errors.count, "error") %>.
      </div>
      <ul class="errors">
        <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control'%>

    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class:'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:'form-control' %>

    <%= f.submit yield(:button_text),class:"btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title,"Editar") %>
<% provide(:button_text,"Editar usuario") %>
<div class="row user">
  <div class="col-md-6 col-md-offset-2">
    <%= render'form' %>
  </div>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<% provide(:title,"Crear usuario") %>
<% provide(:button_text,"Crear usuario") %>
<div class="row signup">
  <div class="col-md-6 col-md-offset-2">
    <h1>Registro</h1>
   <%= render'form' %>
  </div>
</div>

app/views/users/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-2">
        <% @posts.each do |f| %>
        <div><%= link_to f.content %></div>
        <% end %>
      </div>
    </div>
  </div>